### ISSUE TITLE
这个配置文件里怎么跟力扣每日提醒一样

### ISSUE THREAD

**Issue by LeonX86** [bingganhe123/60s-#2]
![image](https://user-images.githubusercontent.com/49100008/154674907-235b9b7e-d8b2-43fd-acdc-a8895281e2c9.png)

**Comment by LeonX86** [comment]
报错

```
Python3.8.1
nonebot-adapter-onebot 2.0.0b1
nonebot2 2.0.0b1

```
  warnings.warn(
02-18 19:52:49 [ERROR] nonebot | Failed to import "nonebot_plugin_read_60s"
Traceback (most recent call last):
  File "bot.py", line 40, in <module>
    nonebot.load_plugin("nonebot_plugin_read_60s")#60s看世界
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 30, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 92, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 181, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/__init__.py", line 2, in <module>
    from .config import Config
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/config.py", line 14, in <module>
    class Config(BaseSettings):
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/config.py", line 18, in Config
    leetcode_qq_friends: list[int]
TypeError: 'type' object is not subscriptable
02-18 19:52:49 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
02-18 19:52:49 [SUCCESS] nonebot | Running NoneBot...
02-18 19:52:49 [DEBUG] nonebot | Loaded adapters: OneBot V11
02-18 19:52:49 [INFO] uvicorn | Started server process [6112]
02-18 19:52:49 [INFO] uvicorn | Waiting for application startup.

**Comment by bingganhe123** [comment]
抱歉给您造成麻烦，请删除#以及后面的内容，这个问题正在解决![IMG_20220218_200356.png](https://user-images.githubusercontent.com/98812723/154679797-a6494eb8-c8c7-4ca0-b77a-548451fbb07e.png)

**Comment by bingganhe123** [comment]
您所提出的所有问题均在0.2.3版本解决，已打包上传，现在下载更新即可

**Comment by LeonX86** [comment]
> 您所提出的所有问题均在0.2.3版本解决，已打包上传，现在下载更新即可


已经更新0.2.3
删除了注释还是会报相同的错
TypeError: 'type' object is not subscriptable

**Comment by bingganhe123** [comment]
可以截一张env配置文件图给我看一下吗

**Comment by LeonX86** [comment]
> 可以截一张env配置文件图给我看一下吗

![image](https://user-images.githubusercontent.com/49100008/154731256-7b56a574-e1d6-4752-bf56-74e3b89c8077.png)

**Comment by bingganhe123** [comment]
我按照您给的截图填写使用并没有报错，请问您在安装新版本的时候是否已经删除旧版本，如果没有的话建议删除后重新安装，0.2.3版本已支持添加注释

**Comment by LeonX86** [comment]
> 我按照您给的截图填写使用并没有报错，请问您在安装新版本的时候是否已经删除旧版本，如果没有的话建议删除后重新安装，0.2.3版本已支持添加注释

重新安装之后还是报错，这次我查看了源码并删除了env文件的全部内容进行测试，发现报错还是一样的
![image](https://user-images.githubusercontent.com/49100008/154784055-7a986d51-42fd-4b7b-a1a8-4d14d6ade4fb.png)

See https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names
  warnings.warn(
02-19 11:14:37 [ERROR] nonebot | Failed to import "nonebot_plugin_read_60s"
Traceback (most recent call last):
  File "bot.py", line 41, in <module>
    nonebot.load_plugin("nonebot_plugin_read_60s")#60s看世界
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 30, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 92, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 181, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/__init__.py", line 2, in <module>
    from .config import Config
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/config.py", line 14, in <module>
    class Config(BaseSettings):
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_read_60s/config.py", line 18, in Config    read_qq_friends: list[int]
TypeError: 'type' object is not subscriptable
02-19 11:14:37 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
02-19 11:14:37 [SUCCESS] nonebot | Running NoneBot...
02-19 11:14:37 [DEBUG] nonebot | Loaded adapters: OneBot V11
02-19 11:14:37 [INFO] uvicorn | Started server process [27011]
02-19 11:14:37 [INFO] uvicorn | Waiting for application startup.
02-19 11:14:37 [INFO] uvicorn | Application startup complete.
02-19 11:14:37 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:53245 (Press CTRL+C to quit)
02-19 11:14:45 [INFO] uvicorn | ('127.0.0.1', 44686) - "WebSocket /onebot/v11/ws/" [accepted]
02-19 11:14:45 [INFO] nonebot | OneBot V11 | Bot 1851377216 connected

**Comment by bingganhe123** [comment]
这个是我的联系方式QQ:2216126625
您可以加一下好友，分析一下问题

**Comment by LeonX86** [comment]
> 我按照您给的截图填写使用并没有报错，请问您在安装新版本的时候是否已经删除旧版本，如果没有的话建议删除后重新安装，0.2.3版本已支持添加注释

我删除了源码config.py文件中的套在int和TIME()外层的list[]进行测试，发现报了不一样的错误
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
read_qq_friends
  field required (type=value_error.missing)
read_qq_groups
  field required (type=value_error.missing)

但是上面任意一行只要有list[]就会报和之前相同的错
